### ISSUE TITLE
rebuilding libhdate-glib on archlinux after update to gnome 3.16 doesn't help

### ISSUE THREAD

**Issue by mat-mo** [amiad/gnome-hdate#11]
Apr 12 23:00:26 arch gnome-session[704]: (gnome-shell:774): Gjs-WARNING **: JS ERROR: Exception in callback for signal: extension-found: Error: Requiring LibHdateGlib, version none: Typelib file for namespace 'LibHdateGlib' (any version) not found

$locate libhdate-glib
/usr/lib/pkgconfig/libhdate-glib.pc
/usr/share/vala-0.28/vapi/libhdate-glib.vapi

**Comment by amiad** [comment]
You updated gnome-shell, restarted gdm, rebuilded libhdate-glib and installed gnome-hdate?
Where you get the error?

**Comment by mat-mo** [comment]
Yes, those are the steps taken. when clicking in extensions.gnome.org https://extensions.gnome.org/extension/554/gnome-hdate/ 

the journal has:

אפר 13 11:16:26 arch gnome-session[704]: Archive:  /tmp/VVP5WX.shell-extension.zip
אפר 13 11:16:26 arch gnome-session[704]: creating: /home/matanya/.local/share/gnome-shell/extensions/hdate@hatul.info/locale/he/LC_MESSAGES/
אפר 13 11:16:26 arch gnome-session[704]: inflating: /home/matanya/.local/share/gnome-shell/extensions/hdate@hatul.info/locale/he/LC_MESSAGES/gnome-hdate.mo
אפר 13 11:16:26 arch gnome-session[704]: inflating: /home/matanya/.local/share/gnome-shell/extensions/hdate@hatul.info/extension.js
אפר 13 11:16:26 arch gnome-session[704]: inflating: /home/matanya/.local/share/gnome-shell/extensions/hdate@hatul.info/po/gnome-hdate.pot
אפר 13 11:16:26 arch gnome-session[704]: extracting: /home/matanya/.local/share/gnome-shell/extensions/hdate@hatul.info/stylesheet.css
אפר 13 11:16:26 arch gnome-session[704]: inflating: /home/matanya/.local/share/gnome-shell/extensions/hdate@hatul.info/po/he.po
אפר 13 11:16:26 arch gnome-session[704]: inflating: /home/matanya/.local/share/gnome-shell/extensions/hdate@hatul.info/README.md
אפר 13 11:16:26 arch gnome-session[704]: inflating: /home/matanya/.local/share/gnome-shell/extensions/hdate@hatul.info/screenshot.png
אפר 13 11:16:26 arch gnome-session[704]: extracting: /home/matanya/.local/share/gnome-shell/extensions/hdate@hatul.info/metadata.json
and then the switcher turns back to off.

when taking the master by hand, the error is comment 1 appears.

**Comment by amiad** [comment]
I could not restore the problem. Try to uninstall libhdate & libhdate-glib and install again.

**Comment by mat-mo** [comment]
done, still no luck.

**Comment by yaacov** [comment]
HI, any news about this ?
Can you try:
https://github.com/yaacov/libhdate-glib/releases/download/v0.5.0/libhdate-glib-0.5.0.tar.bz2

  cd lib...
  ./configure --prefix=/usr
  make
  sudo make install

and then try the examples in the examples dir

**Comment by mat-mo** [comment]
The install works, but the extension refuses to work.

**Comment by yaacov** [comment]
Thank you for trying.

If the examples will not run the install failed :-)
after doing install this files should be in this places (or similar places depending on your system):
./usr/share/gir-1.0
./usr/share/gir-1.0/LibHdateGlib-1.0.gir
./usr/share/vala-0.26
./usr/share/vala-0.26/vapi
./usr/share/vala-0.26/vapi/libhdate.vapi
./usr/share/vala-0.26/vapi/libhdate-glib.vapi
./usr/include
./usr/include/hdate-glib.h
./usr/lib
./usr/lib/x86_64-linux-gnu
./usr/lib/x86_64-linux-gnu/libhdate_glib.so
./usr/lib/x86_64-linux-gnu/girepository-1.0
./usr/lib/x86_64-linux-gnu/girepository-1.0/LibHdateGlib-1.0.typelib
./usr/lib/x86_64-linux-gnu/libhdate_glib.so.0.0.0
./usr/lib/x86_64-linux-gnu/libhdate_glib.so.0
./usr/lib/x86_64-linux-gnu/libhdate_glib.la
./usr/lib/x86_64-linux-gnu/pkgconfig
./usr/lib/x86_64-linux-gnu/pkgconfig/libhdate-glib.pc

can you check where the install install the files in your system ?
can you check where similar files are usually installed in your system ? 
[ for example, on my debian system all typelib files are in  /usr/lib/x86_64-linux-gnu/girepository-1.0/ ]

**Comment by mat-mo** [comment]
Please note, I wrote, the extension, not the examples. The examples work well. It is some funky thing in gnome i fear.

**Comment by yaacov** [comment]
?!
do you mean like this:
==================
on my system, before make install:
> gjs ./examples/test_gjs.js 
>
> (gjs:6845): Gjs-WARNING **: JS ERROR: Error: Requiring LibHdateGlib, version none: Typelib file for namespace 'LibHdateGlib' (any version) not found
> @test_gjs.js:3
> JS_EvaluateScript() failed
 ===================

and then, after make install:
>gjs ./examples/test_gjs.js 
>שלישי May 19 2015, א' סיון התשע"ה
>sunrise - 04:41
>sunset - 18:32
>first_light - 03:18
>talit - 03:47
>first_stars - 19:00
>three_stars - 19:13

**Comment by mat-mo** [comment]
I will try again tomorrow with a clean env.

**Comment by mat-mo** [comment]
fixed long ago, thank you for your help.
