### ISSUE TITLE
add support to gnome 3.18 and above

### ISSUE THREAD

**Issue by amiad** [amiad/gnome-hdate#13]
codemill$3

**Comment by yaacov** [comment]
Just adding 3.18 to metadata.json works for me.

![screenshot from 2016-04-10 17-10-35](https://cloud.githubusercontent.com/assets/2181522/14410770/60b13d76-ff3f-11e5-8bc2-fae489a2c900.jpg)

**Comment by amiad** [comment]
I added 3.18 and 3.20 to metadata.json and I get error in lg (Looking Glass).

```
$ journalctl -b | grep hdate
אפר 10 17:36:13 desktop gnome-session[635]: @/home/amiad/.local/share/gnome-shell/extensions
/hdate@hatul.info/extension.js:17
```

**Comment by yaacov** [comment]
can you run gjs in the terminal ?
`gjs> const Hdate = imports.gi.LibHdateGlib.Hdate;`
do you get an error ?

**Comment by amiad** [comment]
The problem was in package in AUR. I fixed it.
