### ISSUE TITLE
Can you add some of the hebcal functions like shabbos times?

### ISSUE THREAD

**Issue by SolarAquarion** [amiad/gnome-hdate#15]

**Comment by yarons** [comment]
Isn't 3 stars indication enough?

**Comment by SolarAquarion** [comment]
It should for Havdallah, not so for candle lighting

**Comment by amiad** [comment]
I get the times from [libhdate-glib](https://github.com/yaacov/libhdate-glib) library and it not support shabbat times. Even the times of "one star" and "three stars" are inaccurate but I can't fix them.
Contact libhdate-glib developers and ask they add support.
