### ISSUE TITLE
Convert to standard Hebrew unicode symbols

### ISSUE THREAD

**Issue by yarons** [amiad/gnome-hdate#16]
The original libhdate package returns the date with apostrophes and quotes instead of the Hebrew standard Geresh and Gershayim (accordingly), example:
ה'תשע"ה -> ה׳התשע״ה

Is there any way to convert these automatically using some sort of Regex?

**Comment by amiad** [comment]
Yes, I can convert the characters to Hebrew characters but the best way that libhdate will convert them or libhdate-glib. Try to [contact them](https://github.com/yaacov/libhdate-glib).

**Comment by yarons** [comment]
It's higher than this, it's originated from glibc-locale.

**Comment by amiad** [comment]
Open bug there and link here.
I'll wait and if they don't fix then I'll fix it here.

**Comment by yarons** [comment]
https://sourceware.org/bugzilla/show_bug.cgi?id=25970

**Comment by amiad** [comment]
Fixed in upstream
