### ISSUE TITLE
Please update vala dependency

### ISSUE THREAD

**Issue by Coburn** [amiad/gnome-hdate#17]
Current version on Ubuntu 20.04 LTS is libvala-0.48. Will not install with 0.16 as a dependency.

**Comment by amiad** [comment]
I use Arch with Vala 0.48 without any problem.
Where written version 0.16?

**Comment by Coburn** [comment]
I am on Ubuntu 20.04. The 0.16 dependency breaks my install. I just
downloaded it from GitHub, I think.

**Comment by amiad** [comment]
Where Vala 0.16 is dependency?
This is extention to Gnome, Vala isn't direct dependency.

**Comment by Coburn** [comment]
OK I found it. Libvala 0.48 is installed. GDebi installation of
libhdate-glib from the Google page says:

Dependency is not satisfiable: libvala-0.16-0 (>= 0.15.1)

Trying to compile manually from the github site (yaacov/libhdate-glib) says:

configure: error: Package requirements (libhdate >= 1.6.0 libvala-.
glib-2.0 >= 2.12.0 gobject-2.0 >= 2.12.0) were not met:

No package 'libvala-.' found

However, I have libvala and libvala-dev installed. I got it to stop
complaining "no package" for the others (glib, gobject, and libhdate) by
installing the dev versions.

Thanks,

Coby

**Comment by amiad** [comment]
Good.

**Comment by Coburn** [comment]
I don't think you understood. Make returned, "No package 'libvala-.'
found." Why did you close it? I have vala installed but make does not see
it. Libhdate-glib is not installable as written.

Thanks for all your help! I do not think that this Gnome extension will be
resurrected from the dead. But I think it may be the seed of other, better
extensions. I appreciate your work and your willingness to answer questions.

Thanks,

Coby

**Comment by amiad** [comment]
Your problem is not related to my extension but to libhdate-glib package.
I see you opened bug there and Kobi Zamir helping you.
