### ISSUE TITLE
Configure what data is displayed

### ISSUE THREAD

**Issue by shmu26** [amiad/gnome-hdate#18]
Can I remove the ב prefix on the month name, or the ה prefix on the year, or tweak the display on the dash in other ways? 

I see that the holy day and the omer can be removed by deleting the relevant section in the extension.js file. Please inform if there is a more elegant way to hack it.

**Comment by yaacov** [comment]
> Can I remove the ב prefix on the month nam

the ב is part of the code, so you can write a pull request that will make it optional:
https://github.com/amiad/gnome-hdate/blob/master/extension.js#L89

the ה in the year is actually part of the year nuber:
https://he.wikipedia.org/wiki/%D7%94%27_%D7%90%D7%9C%D7%A4%D7%99%D7%9D
 you can write a pull request that will make it optional by taking the modulus from 1000
 https://github.com/amiad/gnome-hdate/blob/master/extension.js#L90

**Comment by amiad** [comment]
I prefer to keep the extension simple and not add preferences menu. But if you will send pull request then I will merge it.
