### ISSUE TITLE
Please update it

### ISSUE THREAD

**Issue by shmu26** [amiad/gnome-hdate#20]
Please get this awesome extension updated if there is any way you can. It would be worth switching to Gnome just for this. It currently causes severe issues with the more recent versions of Gnome shell.

**Comment by amiad** [comment]
It working for me. I use Gnome 44.1 on Arch Linux.

What your problem?

**Comment by shmu26** [comment]
I tried it last week on Gnome 38, running on MX Linux (Based on Debian
Buster). I was unable to lock the session, I mean, to go to lockscreen.
When I tried a second time to go to lockscreen, it crashed the whole
session. This was on xorg, not wayland.

And I will paste a comment I made on
https://extensions.gnome.org/extension/554/gnome-hdate/

On Ubuntu 21.10 it prevents screen locking, when using Xorg.
When using the default Wayland, it causes system freezing and app crashing
when the screen locks.

**Comment by amiad** [comment]
I don't know what the problem. Are there any errors in journalctl?

**Comment by shmu26** [comment]
I hit the lock screen button a couple times, and below is the log. 
I don't know if any of this is relevant, it is from Ubuntu 22.04 with the default wayland session.
Maybe this line is relevant:
`gnome-session-binary[1112]: GLib-GIO-CRITICAL`
I can try it again with xorg, and send the log, if you think it might help.
תודה על הכל
`journalctl -p 3 -xb
May 15 08:38:07 shmuel-VirtualBox kernel: RETBleed: WARNING: Spectre v2 mitigat>
May 15 08:38:09 shmuel-VirtualBox systemd-udevd[306]: vboxguest: /etc/udev/rule>
May 15 08:38:09 shmuel-VirtualBox systemd-udevd[306]: vboxuser: /etc/udev/rules>
May 15 08:38:09 shmuel-VirtualBox kernel: [drm:vmw_host_printf [vmwgfx]] *ERROR>
May 15 08:38:10 shmuel-VirtualBox kernel: snd_intel8x0 0000:00:05.0: measure - >
May 15 08:38:10 shmuel-VirtualBox kernel: snd_intel8x0 0000:00:05.0: measure - >
May 15 08:38:11 shmuel-VirtualBox kernel: snd_intel8x0 0000:00:05.0: measure - >
May 15 08:38:21 shmuel-VirtualBox gnome-session-binary[1112]: GLib-GIO-CRITICAL>
May 15 08:38:21 shmuel-VirtualBox gnome-session-binary[1112]: GLib-GIO-CRITICAL>
May 15 08:38:39 shmuel-VirtualBox gdm-password][1461]: gkr-pam: unable to locat>
May 15 08:38:48 shmuel-VirtualBox pulseaudio[1481]: GetManagedObjects() failed:>
May 15 08:38:49 shmuel-VirtualBox gdm-launch-environment][1060]: GLib-GObject: >
May 15 08:43:43 shmuel-VirtualBox systemd-udevd[4041]: vboxuser: /etc/udev/rule>
May 15 08:43:43 shmuel-VirtualBox systemd-udevd[4033]: vboxguest: /etc/udev/rul>
May 15 09:50:14 shmuel-VirtualBox pulseaudio[1481]: ALSA woke us up to write ne>
May 15 09:50:14 shmuel-VirtualBox pulseaudio[1481]: Most likely this is a bug i>
May 15 09:50:14 shmuel-VirtualBox pulseaudio[1481]: We were woken up with POLLO>
`

**Comment by shmu26** [comment]
correction: the above is from a xorg session
`inxi -F
System:
  Host: shmuel-VirtualBox Kernel: 5.19.0-41-generic x86_64 bits: 64
    Desktop: GNOME 42.5 Distro: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
Machine:
  Type: Virtualbox System: innotek GmbH product: VirtualBox v: 1.2
    serial: <superuser required>
  Mobo: Oracle model: VirtualBox v: 1.2 serial: <superuser required>
    BIOS: innotek GmbH v: VirtualBox date: 12/01/2006
CPU:
  Info: dual core model: Intel Core i7-9700 bits: 64 type: MCP cache:
    L2: 512 KiB
  Speed (MHz): avg: 3000 min/max: N/A cores: 1: 3000 2: 3000
Graphics:
  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.20.0.0
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: vmware
    unloaded: fbdev,modesetting,vesa gpu: vmwgfx resolution: 1912x281~60Hz
  OpenGL: renderer: llvmpipe (LLVM 15.0.6 256 bits) v: 4.5 Mesa 22.2.5
Audio:
  Device-1: Intel 82801AA AC97 Audio driver: snd_intel8x0
  Sound Server-1: ALSA v: k5.19.0-41-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel 82540EM Gigabit Ethernet driver: e1000
  IF: enp0s3 state: up speed: 1000 Mbps duplex: full mac: 08:00:27:51:93:41
  Device-2: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge
    driver: piix4_smbus
Drives:
  Local Storage: total: 50.04 GiB used: 93.26 GiB (186.4%)
  ID-1: /dev/sda vendor: VirtualBox model: VBOX HARDDISK size: 50.04 GiB
Partition:
  ID-1: / size: 48.46 GiB used: 14.13 GiB (29.2%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 512 MiB used: 6.1 MiB (1.2%) fs: vfat
    dev: /dev/sda2
Swap:
  ID-1: swap-1 type: file size: 3.81 GiB used: 2 MiB (0.1%) file: /swapfile
Sensors:
  Message: No sensor data found. Is lm-sensors configured?
Info:
  Processes: 205 Uptime: 1h 34m Memory: 2.33 GiB used: 1.12 GiB (48.1%)
  Shell: Bash inxi: 3.3.13
`

**Comment by amiad** [comment]
I not see relevant errors. Maybe the problem related to Virtualbox.
