### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by shmu26** [amiad/gnome-hdate#21]
Hi, I discovered that it is pretty easy to get the Hebrew date on the panel in recent versions of Gnome by using `Executor`
https://github.com/raujonas/executor

with `Hebcal`
https://github.com/hebcal/hebcal
as a dependency. 

In `Executor` you enter the command:
`hebcal -T --lang he`
and voila you have the Hebrew date displayed. To get the output in the default system language, the command is simply
`hebcal -T`

On special days, such as Rosh Chodesh, there probably won't be enough room for the whole output, but it should still display the date. 

Just sharing an idea. I did it also on Plasma and Xfce, with the appropriate extension for command output.

**Comment by yarons** [comment]
Great idea, Plasma recently introduced full Hebrew calendar support:
https://bugs.kde.org/show_bug.cgi?id=463869
Tell me if you find anything missing there and I can try and help ask them to fix it.

**Comment by yarons** [comment]
Kudos to the Chinese guy that doesn't speak a word of Hebrew or Arabic and implemented both Jewish and Hijra calendars flawlessly. 🤣
He might have also implemented the Persian calendar and he did it with other calendars as well before, pretty awesome dude.
